export const WARNING_BOTH_AVAIL_BLOCKED_DEFINED =
  "Both availableDates and blockedDates props are defined for <Calendar /> component. To avoid unexpected behavior and errors, in this case both are treated as undefined and all days will be styled as available. Please specify only one option and leave the other undefined";

export const DAYS_ARRAY = [
  "28",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "20",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
  "27",
  "28",
  "29",
  "30",
  "31",
  "1",
  "2",
  "3",
];
